export const videos = [
  { id: 1, url: 'https://www.youtube.com/watch?v=unL5iLEIJFM' },
  { id: 2, url: 'https://www.youtube.com/watch?v=uverlaEjJMg' },
  { id: 3, url: 'https://www.youtube.com/watch?v=9ENTDWTju2Q' },
  { id: 4, url: 'https://www.youtube.com/watch?v=fZVbHnQAlGY' },
  { id: 5, url: 'https://www.youtube.com/watch?v=aL9i7GwPn9I' },
  { id: 6, url: 'https://www.youtube.com/watch?v=9KbSmuNlKQg' },
  //{ id: 7, url: 'https://www.youtube.com/watch?v=Lk3SNSgBZkQ&t=3s' },
  { id: 8, url: 'https://www.youtube.com/watch?v=W0f3eKnySeM&t=2s' },
  { id: 9, url: 'https://www.youtube.com/watch?v=9ylOvd3cspY&t=1s' },
  { id: 10, url: 'https://www.youtube.com/watch?v=_yHNO4cf-Vw' },
  { id: 11, url: 'https://www.youtube.com/watch?v=-qeoYLRAxao' },
  { id: 12, url: 'https://www.youtube.com/watch?v=YynVFNOln8g' },
  //{ id: 13, url: 'https://www.youtube.com/watch?v=YynVFNOln8g' },
  { id: 14, url: 'https://www.youtube.com/watch?v=3SjY_Je3yCY' },
  { id: 15, url: 'https://www.youtube.com/watch?v=9dJINqILLwQ' },
  { id: 16, url: 'https://www.youtube.com/watch?v=LoqMVU19_5M' },
  { id: 17, url: 'https://www.youtube.com/watch?v=SzeAsTYYW-w' },
  { id: 18, url: 'https://www.youtube.com/watch?v=QUV4xbOseaA' },
  { id: 19, url: 'https://www.youtube.com/watch?v=L50vFW4emFA' },
  { id: 20, url: 'https://www.youtube.com/watch?v=fPgENQ-WZiQ' },
  { id: 21, url: 'https://www.youtube.com/watch?v=DIHf4DWGglE&t=37s' },
  { id: 22, url: 'https://www.youtube.com/watch?v=L3mDvkW0ezU' },
];
